name: firebase_login
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  circular_bottom_navigation: ^2.1.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

